name: Translate README

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # ISO Language Codes: https://cloud.google.com/translate/docs/languages  
      - name: Adding README - Brazilian Portuguese
        uses: hugosouto/comprasgov-modo-disputa-obras@main
        with:
          LANG: pt-br